language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CARGO_C_LINK=https://github.com/lu-zero/cargo-c/releases/download
addons:
  apt:
    packages:
      - valgrind
script:
  - wget https://tech.ebu.ch/files/live/sites/tech/files/shared/testmaterial/ebu-loudness-test-setv05.zip
  - unzip -u ebu-loudness-test-setv05.zip -d tests/reference_files
  - curl -L $CARGO_C_LINK/v0.6.12/cargo-c-linux.tar.gz |
    tar xz -C $HOME/.cargo/bin
  - QUICKCHECK_TESTS=2 cargo test --features c-tests,internal-tests,reference-tests
  - cargo clean
  - cargo cinstall --prefix=`pwd`/install
  - PKG_CONFIG_PATH=`pwd`/install/lib/pkgconfig make -C capi-test check
  - PKG_CONFIG_PATH=`pwd`/install/lib/pkgconfig make -C capi-test check-valgrind
matrix:
  allow_failures:
    - rust: nightly
